# Atomic service targets.
# Called by deploy.yml via make: steps and can also be used standalone.
# Variables come from .env (generated by devbox render env).

.PHONY: app-install config-copy-main db-create composer-install key-generate migrate cli cli-root

mode ?= exec

app-install:
	@docker compose --progress tty -p $(PROJECT_FULL) -f compose/installer.yml run --rm --quiet-pull -u $$(id -u):$$(id -g) app-install
	@$(call ok,Laravel project installed)

config-copy-main:
	@$(DEVBOX_BIN) deploy config main
	@$(call ok,Configs copied)

db-create:
	@$(DOCKER_COMPOSE) exec db mariadb -uroot -p$(DB_PASSWORD) \
		-e 'CREATE DATABASE IF NOT EXISTS `$(DB_DATABASE)` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
	@$(call ok,Database $(DB_DATABASE) created)

composer-install:
	@if $(call container-running,$(APP_MAIN_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			composer install --ansi --prefer-dist --no-interaction --optimize-autoloader; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			composer install --ansi --prefer-dist --no-interaction --optimize-autoloader; \
	fi
	@$(call ok,Composer install complete)

key-generate:
	@$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
		php artisan key:generate
	@$(call ok,Application key generated)

migrate:
	@$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
		php artisan migrate
	@$(call ok,Migrations complete)

cli:
	@$(DOCKER_COMPOSE) $(mode) -it -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) bash

cli-root:
	@$(DOCKER_COMPOSE) $(mode) -it -u root -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) bash
