# Atomic service targets.
# Called by deploy.yml via make: steps and can also be used standalone.
# Variables come from .env (generated by devbox render env).

.PHONY: app-install config-copy-main db-start db-create composer-install key-generate migrate cli cli-root

mode ?= exec

app-install:
	@docker compose --progress tty -p $(PROJECT_FULL) -f compose/installer.yml run --rm --quiet-pull -u $$(id -u):$$(id -g) app-install
	@$(call ok,Laravel project installed)

config-copy-main:
	@$(DEVBOX_BIN) deploy config main
	@$(call ok,Configs copied)

db-start:
	@$(DOCKER_COMPOSE) up -d db
	@$(DEVBOX_BIN) compose wait
	@$(call ok,Database container is healthy)

db-create: db-start
	@$(DOCKER_COMPOSE) exec db mariadb -uroot -p$(DB_PASSWORD) \
		-e 'CREATE DATABASE IF NOT EXISTS `$(DB_DATABASE)` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
	@$(call ok,Database $(DB_DATABASE) created)

composer-install:
	@if $(call container-running,$(APP_MAIN_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			composer install --ansi --prefer-dist --no-interaction --optimize-autoloader; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			composer install --ansi --prefer-dist --no-interaction --optimize-autoloader; \
	fi
	@$(call ok,Composer install complete)

key-generate:
	@if $(call container-running,$(APP_MAIN_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			php artisan key:generate; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			php artisan key:generate; \
	fi
	@$(call ok,Application key generated)

migrate:
	@if $(call container-running,$(APP_MAIN_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			php artisan migrate; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
			php artisan migrate; \
	fi
	@$(call ok,Migrations complete)

cli:
	@$(DOCKER_COMPOSE) $(mode) -it -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) bash

cli-root:
	@$(DOCKER_COMPOSE) $(mode) -it -u root -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) bash

# Second service targets
# APP_SECOND_CONTAINER and APP_SECOND_DIR_INTERNAL come from .env (exported when second is enabled).
# Fallback values match the compose service name and internal path defaults.

APP_SECOND_CONTAINER ?= app-second
APP_SECOND_DIR_INTERNAL ?= /workspace/src
DB_SECOND_DATABASE ?= laravel_second

.PHONY: db-create-second composer-install-second key-generate-second migrate-second cli-second cli-second-root

db-create-second: db-start
	@$(DOCKER_COMPOSE) exec db mariadb -uroot -p$(DB_PASSWORD) \
		-e 'CREATE DATABASE IF NOT EXISTS `$(DB_SECOND_DATABASE)` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
	@$(call ok,Database $(DB_SECOND_DATABASE) created)

composer-install-second:
	@if $(call container-running,$(APP_SECOND_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) \
			composer install --ansi --prefer-dist --no-interaction --optimize-autoloader; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) \
			composer install --ansi --prefer-dist --no-interaction --optimize-autoloader; \
	fi
	@$(call ok,Composer install complete for second)

key-generate-second:
	@if $(call container-running,$(APP_SECOND_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) \
			php artisan key:generate; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) \
			php artisan key:generate; \
	fi
	@$(call ok,Application key generated for second)

migrate-second:
	@if $(call container-running,$(APP_SECOND_CONTAINER)); then \
		$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) \
			php artisan migrate; \
	else \
		$(DOCKER_COMPOSE) run --rm --no-deps -u $$(id -u) -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) \
			php artisan migrate; \
	fi
	@$(call ok,Migrations complete for second)

cli-second:
	@$(DOCKER_COMPOSE) $(mode) -it -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) bash

cli-second-root:
	@$(DOCKER_COMPOSE) $(mode) -it -u root -w $(APP_SECOND_DIR_INTERNAL) $(APP_SECOND_CONTAINER) bash
