# Atomic service targets.
# Called by deploy.yml via make: steps and can also be used standalone.
# Variables come from .env (generated by devbox render env).

IMAGE_APP_INSTALLER ?= composer:2

.PHONY: db_create composer_install key_generate migrate

db_create:
	@$(DOCKER_COMPOSE) exec db mariadb -uroot -p$(DB_PASSWORD) \
		-e 'CREATE DATABASE IF NOT EXISTS `$(DB_DATABASE)` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
	@$(call ok,Database $(DB_DATABASE) created)

# IMAGE_APP_INSTALLER defaults to composer:2 which bundles its own PHP.
# If your app image uses a non-default PHP version, set IMAGE_APP_INSTALLER
# in devbox/local.yml to an image matching your PHP version.
composer_install:
	@docker run --rm -u $$(id -u) \
		-v "$$(pwd)/services/main/src:/app" \
		-w /app \
		$(IMAGE_APP_INSTALLER) install --prefer-dist --no-interaction --optimize-autoloader
	@$(call ok,Composer install complete)

key_generate:
	@$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
		php artisan key:generate
	@$(call ok,Application key generated)

migrate:
	@$(DOCKER_COMPOSE) exec -u $$(id -u) -w $(APP_MAIN_DIR_INTERNAL) $(APP_MAIN_CONTAINER) \
		php artisan migrate
	@$(call ok,Migrations complete)
